var categories = {
  "access": "Access Software",
  "activision": "Activision",
  "adventuresoft": "Adventure/Horror Soft",
  "animagic": "Animation Magic",
  "coktel": "Coktel Vision",
  "cyan": "Cyan Worlds",
  "delphine": "Delphine Software",
  "fan": "Fan Games",
  "gda": "Gray Design Associates",
  "humongous": "Humongous Entertainment",
  "if": "Interactive Fiction",
  "living": "Living Books",
  "lucasarts": "LucasArts",
  "composer": "Magic Tales",
  "origin": "Origin Systems",
  "other": "Other Games",
  "nwc": "New World Computing",
  "polarware": "Polarware",
  "presto": "Presto Studios",
  "revolution": "Revolution Studios",
  "sierra": "Sierra",
  "tsunami": "Tsunami Games",
  "westwood": "Westwood Studios"
};
